University_For_All/Models/Course.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace University_For_All.Models
{
    public class Course
    {
        public int id { get; set; }
        [Required]
        public string cr_title { get; set; }
        [Required]
        [Range(1,3)]
        public int cr_credit_hours { get; set; }
        [Required]
        [Range(1,2)]
        public int cr_term { get; set; }
        [Required]
        [Range(1,7)]
        public int cr_level { get; set; }
        public Faculty Faculty { get; set; }
        [Required]
        public int Facultyid { get; set; }
        public Instructor Instructor { get; set; }
        public int? Instructorid { get; set; }

        
    }
}

University_For_All/Models/Department.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace University_For_All.Models
{
    public class Department
    {
        public int id { get; set; }
        [Display(Name = "Department Name")]
        [Required]
        public string name { get; set; }
        [Required]
        public string description { get; set; }
        public Faculty Faculty { get; set; }
        [Required(ErrorMessage = "Faculty is Required")]
        public int Facultyid { get; set; }
    }
}

University_For_All/Models/Faculty.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace University_For_All.Models
{
    public class Faculty
    {
        public int id { get; set; }
        [Display(Name = "Faculty Name")]
        [Required]
        public string fc_name { get; set; }
        [Display(Name = "Description")]
        [Required]
        public string fc_description { get; set; }
        [Required]
        [DataType(DataType.Date)]
        [Display(Name = "Created at")]
        public DateTime fc_created_at { get; set; }
        [Required]
        [Range(1,7)]
        [Display(Name = "Number Of Levels")]

        public int fc_levels_num { get; set; }
        [Range(1,3)]
        [Required]
        [Display(Name = "Special Year")]

        public int fc_spicial_year { get; set; }
        public string fc_logo { get; set; }
    }
}

University_For_All/Controllers/CoursesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using University_For_All.Models;

namespace University_For_All.Controllers
{
    public class CoursesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Courses
        public ActionResult Index()
        {
            var courses = db.Courses.Include(c => c.Faculty).Include(c => c.Instructor);
            return View(courses.ToList());
        }

        // GET: Courses/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course = db.Courses.Include(c=>c.Faculty).Include(c=>c.Instructor).SingleOrDefault(c=>c.id==id);
            if (course == null)
            {
                return HttpNotFound();
            }
            return View(course);
        }

        // GET: Courses/Create
        public ActionResult Create()
        {
            ViewBag.Facultyid = new SelectList(db.Faculty, "id", "fc_name");
            ViewBag.Instructorid = new SelectList(db.Instructors, "id", "ints_fname");
            if (db.Courses.Count()==0 && db.Faculty.Count()==0)
            {
                return Content("Please add Faculty and Staff First");
            }
            return View();
        }
        public JsonResult GetStaffList(int id)
        {
            db.Configuration.ProxyCreationEnabled = false;
            var staffList = db.Instructors.Where(d => d.Facultyid == id).ToList();
            return Json(staffList, JsonRequestBehavior.AllowGet);
        }

        // POST: Courses/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,cr_title,cr_credit_hours,cr_term,cr_level,Facultyid,Instructorid")] Course course)
        {
            if (ModelState.IsValid)
            {
                db.Courses.Add(course);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Facultyid = new SelectList(db.Faculty, "id", "fc_name", course.Facultyid);
            ViewBag.Instructorid = new SelectList(db.Instructors, "id", "ints_fname", course.Instructorid);
            return View(course);
        }

        // GET: Courses/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course = db.Courses.Find(id);
            if (course == null)
            {
                return HttpNotFound();
            }
            ViewBag.Facultyid = new SelectList(db.Faculty, "id", "fc_name", course.Facultyid);
            ViewBag.Instructorid = new SelectList(db.Instructors, "id", "ints_fname", course.Instructorid);
            return View(course);
        }

        // POST: Courses/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,cr_title,cr_credit_hours,cr_term,cr_level,Facultyid,Instructorid")] Course course)
        {
            if (ModelState.IsValid)
            {
                db.Entry(course).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Facultyid = new SelectList(db.Faculty, "id", "fc_name", course.Facultyid);
            ViewBag.Instructorid = new SelectList(db.Instructors, "id", "ints_fname", course.Instructorid);
            return View(course);
        }

        // GET: Courses/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course = db.Courses.Include(c => c.Faculty).Include(c => c.Instructor).SingleOrDefault(c => c.id == id);
            if (course == null)
            {
                return HttpNotFound();
            }
            return View(course);
        }

        // POST: Courses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Course course = db.Courses.Find(id);
            db.Takes.RemoveRange(db.Takes.Where(t=>t.Courseid==course.id));
            db.Courses.Remove(course);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

University_For_All/Controllers/DepartmentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using University_For_All.Models;

namespace University_For_All.Controllers
{
    public class DepartmentsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Departments
        public ActionResult Index()
        {
            var departments = db.Departments.Include(d => d.Faculty);
            return View(departments.ToList());
        }

        // GET: Departments/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Department department = db.Departments.Find(id);
            if (department == null)
            {
                return HttpNotFound();
            }
            return View(department);
        }

        // GET: Departments/Create
        public ActionResult Create()
        {
            
            ViewBag.Facultyid = new SelectList(db.Faculty, "id", "fc_name");
            if (db.Faculty.Count()==0)
            {
                return Content("Please Add Faculty First");
            }
            return View();
        }

        // POST: Departments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,name,description,Facultyid")] Department department)
        {
            if (ModelState.IsValid)
            {
                db.Departments.Add(department);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Facultyid = new SelectList(db.Faculty, "id", "fc_name", department.Facultyid);
            return View(department);
        }

        // GET: Departments/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Department department = db.Departments.Find(id);
            if (department == null)
            {
                return HttpNotFound();
            }
            ViewBag.Facultyid = new SelectList(db.Faculty, "id", "fc_name", department.Facultyid);
            return View(department);
        }

        // POST: Departments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,name,description,Facultyid")] Department department)
        {
            if (ModelState.IsValid)
            {
                db.Entry(department).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Facultyid = new SelectList(db.Faculty, "id", "fc_name", department.Facultyid);
            return View(department);
        }

        // GET: Departments/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Department department = db.Departments.Find(id);
            if (department == null)
            {
                return HttpNotFound();
            }
            return View(department);
        }

        // POST: Departments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Department department = db.Departments.Find(id);
            db.Departments.Remove(department);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

University_For_All/Controllers/FacultyController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using University_For_All.Models;
using System.Data.Entity;

namespace University_For_All.Controllers
{
    public class FacultyController : Controller
    {
        private ApplicationDbContext db =new ApplicationDbContext();
        // GET: Faculty
        [HttpGet]
        public ActionResult Index()
        {
            var facutlies = db.Faculty.ToList();
            return View(facutlies);
        }
        [HttpGet]
        public ActionResult New()
        {
            return View();
        }
        [HttpPost]
        public ActionResult New(Faculty faculty, HttpPostedFileBase upload)
        {
            var equalFaculty = db.Faculty.SingleOrDefault(f => f.fc_name == faculty.fc_name);
            if (ModelState.IsValid)
            {
                if (upload != null)
                {
                    var path = Path.Combine(Server.MapPath("~/Upload/FacultyImage"), upload.FileName);
                    upload.SaveAs(path);
                }

                if (equalFaculty ==null)
                {
                    faculty.fc_logo = upload == null ? "~/Upload/defaultImage/Faculty_default.png" : "~/Upload/FacultyImage/" + upload.FileName;
                    if (upload == null)
                    {
                        System.IO.File.Copy(Server.MapPath("~/Upload/defaultImage/Faculty_default.png"), Server.MapPath("~/Upload/FacultyImage/Faculty_default.png"), true);

                    }
                    db.Faculty.Add(faculty);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Edit(int? id)
        {
            var faculty = db.Faculty.SingleOrDefault(f => f.id == id);
            
            return View(faculty);
        }
        [HttpPost]
        public ActionResult Save(Faculty faculty,HttpPostedFileBase upload,int id)
        {
            var facultyEdited = db.Faculty.SingleOrDefault(f => f.id == id);
            var oldImg = facultyEdited.fc_logo.Substring(22);
            facultyEdited.fc_name = faculty.fc_name;
            facultyEdited.fc_description = faculty.fc_description;
            if (upload !=null)
            {
                System.IO.File.Delete(Server.MapPath("~/Upload/FacultyImage/") + oldImg);
                var path = Path.Combine(Server.MapPath("~/Upload/FacultyImage"), upload.FileName);
                upload.SaveAs(path);
                facultyEdited.fc_logo = "~/Upload/FacultyImage/" + upload.FileName;
            }
            db.SaveChanges();
            var student = db.Student.Where(s => s.FacultyId == id).ToList();
            if (student.Count!=0)
            {
                foreach (var st in student)
                {
                    st.Faculty.fc_name = facultyEdited.fc_name;
                    db.SaveChanges();
                }
            }
            
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Delete(int? id)
        {
            var faculty = db.Faculty.SingleOrDefault(f => f.id == id);
            return View(faculty);
        }
        [HttpPost]
        public ActionResult Delete(Faculty faculty)
        {
            var studentInthisFaculty = db.Student.Where(s => s.FacultyId == faculty.id).ToList();
            var InstructorInthisFaculty = db.Instructors.Where(I => I.Facultyid == faculty.id).ToList();
            var oldImg = faculty.fc_logo.Substring(22);
            foreach (var student in studentInthisFaculty)
            {
                db.Takes.Remove(db.Takes.Single(t=>t.Studentid==student.id));
                db.SaveChanges();
            }
            foreach (var instructor in InstructorInthisFaculty)
            {
                db.Instructors.Remove(db.Instructors.Single(I => I.id == instructor.id));
                db.SaveChanges();
            }
            System.IO.File.Delete(Server.MapPath("~/Upload/FacultyImage/") + oldImg);
            db.Faculty.Remove(db.Faculty.Single(f => f.id == faculty.id));
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Details(int? id)
        {
            var faculty = db.Faculty.SingleOrDefault(f => f.id == id);
            ViewBag.id = id;
            return View(faculty);
        }
        [HttpGet]
        public ActionResult Staff(int id)
        {
            var staff = db.Instructors.Include(s => s.Faculty).Where(I=>I.Facultyid==id).ToList();
            ViewBag.id = id;
            return View("Staff",staff);
        }
        public ActionResult Departments(int id)
        {
            var department = db.Departments.Include(s => s.Faculty).Where(I => I.Facultyid == id).ToList();
            ViewBag.id = id;
            return View(department);
        }
        public ActionResult Courses(int id)
        {
            var course = db.Courses.Include(s => s.Faculty).Include(s=>s.Instructor).Where(I => I.Facultyid == id).ToList();
            ViewBag.id = id;
            return View(course);
        }
        public ActionResult Students(int id)
        {
            var student = db.Student.Include(s => s.Faculty).Where(I => I.FacultyId == id).ToList();
            ViewBag.id = id;
            return View(student);
        }
    }
}

University_For_All/Views/Faculty/Courses.cshtml
@model IEnumerable<University_For_All.Models.Course>

@{
    ViewBag.Title = "Faculty-Courses";
    Layout = "~/Views/Faculty/_FacultyDetailsLayout.cshtml";
}

<style>
    .cards {
        display: flex;
        flex-direction: row;
        flex-wrap: wrap;
        align-content: flex-start;
        max-height: 200vh;
    }

    .card {
        width: 250px;
        margin: 10px;
        border: 1px solid #ccc;
        box-shadow: 2px 2px 6px 0px rgba(0,0,0,0.3);
    }

    .card img {
        width: 100%;
        max-height: 150px;
    }

    .card .text {
        padding: 0 20px 20px;
    }

    .card .text > .button {
        background: gray;
        border: 0;
        color: white;
        padding: 10px;
        width: 100%;
    }
</style>

<h2 style="text-align: center">Courses Cards</h2>
<main class="container cards ">
    
    @foreach(var course in Model)
    { 
        <article class="card">
            <h1 align="center">@course.cr_title</h1>
            <div class="card-body">
                Credit Hours: @course.cr_credit_hours <br/>
                Studey In Level : @course.cr_level
                Instructor Name : @string.Concat(course.Instructor.ints_fname," ",course.Instructor.inst_lname)<br/>

                
            </div>
            @if (User.IsInRole("admin"))
            {
                @Html.ActionLink("More Info", "Details", "Courses", new { id = course.id }, new { @class = " btn btn-outline-secondary" })
            }
        </article>
    }
</main>

University_For_All/Views/Faculty/Delete.cshtml
@model University_For_All.Models.Faculty

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Faculty/_FacultyLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Faculty</h4>
    <hr />
    <dl class="dl-horizontal">
        <dd>
            @Html.DisplayFor(model => model.fc_logo)
           
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.fc_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fc_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.fc_description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fc_description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.fc_created_at)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fc_created_at)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.fc_levels_num)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fc_levels_num)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.fc_spicial_year)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fc_spicial_year)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.fc_logo)
        </dt>
    </dl>

    @using (Html.BeginForm("Delete","Faculty",FormMethod.Post)) {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(f=>f.id)
        @Html.HiddenFor(model => model.fc_logo)
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

University_For_All/Views/Faculty/Departments.cshtml
@model IEnumerable<University_For_All.Models.Department>

@{
    ViewBag.Title = "Faculty-Departments";
    Layout = "~/Views/Faculty/_FacultyDetailsLayout.cshtml";
}

<style>
    .cards {
        display: flex;
        flex-direction: row;
        flex-wrap: wrap;
        align-content: flex-start;
        max-height: 200vh;
    }

    .card {
        width: 250px;
        margin: 10px;
        border: 1px solid #ccc;
        box-shadow: 2px 2px 6px 0px rgba(0,0,0,0.3);
    }

    .card img {
        width: 100%;
        max-height: 150px;
    }

    .card .text {
        padding: 0 20px 20px;
    }

    .card .text > .button {
        background: gray;
        border: 0;
        color: white;
        padding: 10px;
        width: 100%;
    }
</style>

<h2 style="text-align: center">Departments Cards</h2>
<main class="container cards ">
    
    @foreach(var department in Model)
    { 
        <article class="card">
            <h1 align="center">@department.name</h1>
            <hr/>
            <div class="card-body">
                @department.description
            </div>
            @if (User.IsInRole("admin"))
            {
                @Html.ActionLink("More Info", "Details", "Departments", new { id = department.id }, new { @class = "btn btn-outline-secondary" })

            }
        </article>
    }
</main>

University_For_All/Views/Faculty/Details.cshtml
@model University_For_All.Models.Faculty

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Faculty/_FacultyDetailsLayout.cshtml";
}

<img src="@Url.Content(Model.fc_logo)" alt="@Model.fc_name Logo" style="height: 200px; max-height: 100%; width:100%;max-width: 100%"/>   
<h1 align="center">@Model.fc_name</h1>
<hr style="text-align: center; font-weight: bold;color: darkgray"/>
<p align="center">@Model.fc_description</p> 

University_For_All/Views/Faculty/Edit.cshtml
@model University_For_All.Models.Faculty

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Faculty/_FacultyLayout.cshtml";
}


@using (@Html.BeginForm("Save", "Faculty", FormMethod.Post, new { enctype = "multipart/form-data" }))
{ 
    <div class="col-md-10">
        <div class="image-upload">
            <label for="file-input">
                <img id="image_preview" src="@Url.Content(Model.fc_logo)" title="change Image" style="cursor: pointer; width: 100px; height: 100px; border-radius: 50%;" />
            </label>

            <input id="file-input" name="upload" type="file" onchange="readfile(this)" style="display: none" />
        </div>
    </div>
    @Html.ValidationMessageFor(model => @Model.fc_logo, "", new { @class = "text-danger" })
    <div>
        @Html.LabelFor(f => f.fc_name)
        @Html.TextBoxFor(f => f.fc_name, new { @class = "form-control" })

    </div>

    <div>
        @Html.LabelFor(f => f.fc_description)
        @Html.TextBoxFor(f => f.fc_description, new { @class = "form-control" })
    </div>
    @Html.HiddenFor(f => f.id)
    <button type="submit" class="btn btn-primary">Save</button>
}
    <script type="text/javascript">

    function readfile(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#image_preview').attr('src', e.target.result);
            }

            reader.readAsDataURL(input.files[0]);
        }
    }
</script>

University_For_All/Views/Faculty/Index.cshtml
@using University_For_All.Models
@model IEnumerable<University_For_All.Models.Faculty>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Faculty/_FacultyLayout.cshtml";
}
@{
    var right = true;

}
<section class="creative">
    @foreach (var faculty in @Model)
    {
        if (right)
        {
            <div class="right">
               
                    <a href="/Faculty/Details?id=@faculty.id">
                        <h1>@faculty.fc_name</h1><img src="@Url.Content(faculty.fc_logo)">
                    </a>
            </div>
            right = false;
        }
        else
        {
            <div class="left">
                <a href="/Faculty/Details?id=@faculty.id">
                        <h1>@faculty.fc_name</h1><img src="@Url.Content(faculty.fc_logo)">
                    </a>
            </div>
            right = true;
        }
    }
</section>

University_For_All/Views/Faculty/New.cshtml
@model University_For_All.Models.Faculty

@{
    ViewBag.Title = "New";
    Layout = "~/Views/Faculty/_FacultyLayout.cshtml";
}

@using (Html.BeginForm("New", "Faculty", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.fc_logo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="image-upload">
                <label for="file-input">
                    <img id="image_preview" src="~/images/male-student-icon-png_251938.jpg" style="cursor: pointer; width: 100px; height: 100px; border-radius: 50%;" />
                </label>

                <input id="file-input" name="upload" type="file" onchange="readfile(this)" style="display: none" />
            </div>
            @Html.ValidationMessageFor(model => model.fc_logo, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fc_name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fc_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fc_name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.fc_description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fc_description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fc_description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fc_created_at, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fc_created_at, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fc_created_at, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fc_levels_num, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fc_levels_num, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fc_levels_num, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fc_spicial_year, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fc_spicial_year, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fc_spicial_year, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script type="text/javascript">

    function readfile(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#image_preview').attr('src', e.target.result);
            }

            reader.readAsDataURL(input.files[0]);
        }
    }
</script>

University_For_All/Views/Faculty/Staff.cshtml
@using University_For_All.Models
@model IEnumerable<University_For_All.Models.Instructor>
@{
    ViewBag.Title = "Faculty-Staff";
    Layout = "~/Views/Faculty/_FacultyDetailsLayout.cshtml";
}
@{
    var right = true;
    var db = new ApplicationDbContext();
    var staffFaculty = db.Instructors.SingleOrDefault(i => i.ints_email == User.Identity.Name);
    var studentfaculty = db.Student.SingleOrDefault(i => i.st_email == User.Identity.Name);
    int result = -1;
    if (User.IsInRole("professor"))
    {
        result = staffFaculty.id;
    }
    else if (User.IsInRole("student"))
    {
        result = studentfaculty.id;
    }

}
<style>
    .cards {
        display: flex;
        flex-direction: row;
        flex-wrap: wrap;
        align-content: flex-start;
        max-height: 200vh;
    }

    .card {
        width: 250px;
        margin: 10px;
        border: 1px solid #ccc;
        box-shadow: 2px 2px 6px 0px rgba(0,0,0,0.3);
    }

        .card img {
            width: 100%;
            max-height: 150px;
        }

        .card .text {
            padding: 0 20px 20px;
        }

            .card .text > .button {
                background: gray;
                border: 0;
                color: white;
                padding: 10px;
                width: 100%;
            }
</style>

<h2 style="text-align: center">Staff Cards</h2>
<main class="container cards ">
    
    @foreach(var staff in Model)
    { 
        <article class="card">
            <img class="img-responsive" src="@Url.Content(@staff.inst_picture)" alt="picture for @staff.inst_lname">
            <div class="card-body">
                <h3><b>@string.Join(" ", staff.ints_fname, staff.inst_lname)</b></h3>
                <h5> @staff.Faculty.fc_name</h5>
               
            </div>
            @if (User.IsInRole("admin"))
            {
                @Html.ActionLink("More Info", "Details", "Staff", new { id = staff.id }, new { @class = "btn btn-outline-secondary" })
            }
            else if (User.IsInRole("professor") && staff.id == result)
            {
                @Html.ActionLink("More Info", "Details", "Staff", new { id = staff.id }, new { @class = "btn btn-outline-secondary" })
            }
        </article>
    }
</main>